_BASE_: "../Base-Strongerbaseline.yml"

MODEL:
  BACKBONE:
    DEPTH: "101x"
    WITH_IBN: True
    PRETRAIN_PATH: "/home/ywu/.cache/torch/checkpoints/resnet101_ibn_a.pth.tar"

  HEADS:
    NUM_CLASSES: 751

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: "logs/market1501/sbs_R101-ibn"
