_BASE_: "../Base-Strongerbaseline.yml"

MODEL:
  BACKBONE:
    DEPTH: 101
    WITH_IBN: True
    PRETRAIN_PATH: "/home/ywu/.cache/torch/checkpoints/resnet101_ibn_a.pth.tar"

  HEADS:
    NUM_CLASSES: 751

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

SOLVER:
  MAX_ITER: 36000
  IMS_PER_BATCH: 32

  DELAY_ITERS: 18000

  WARMUP_ITERS: 4000

  FREEZE_ITERS: 4000

  LOG_PERIOD: 400
  CHECKPOINT_PERIOD: 4000
  
TEST:
  PRECISE_BN:
    DATASET: 'Market1501'

OUTPUT_DIR: "logs/market1501/sbs-R101-ibn-3"
