_BASE_: "../Base-Strongerbaseline.yml"

MODEL:
  BACKBONE:
    DEPTH: 101
    WITH_IBN: True
    PRETRAIN_PATH: "/home/ywu/.cache/torch/checkpoints/resnet101_ibn_a.pth.tar"
    NORM: 'syncBN'

  HEADS:
    NUM_CLASSES: 751
    NORM: 'syncBN'

SOLVER:
  MAX_ITER: 36000

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)
  
TEST:
  PRECISE_BN:
    DATASET: 'Market1501'

OUTPUT_DIR: "logs/market1501/sbs-R101-ibn-2gpu-x2"
