_BASE_: "../Base-Strongerbaseline.yml"

MODEL:
  BACKBONE:
    DEPTH: 101
    WITH_IBN: True
    PRETRAIN_PATH: "/home/ywu/.cache/torch/checkpoints/resnet101_ibn_a.pth.tar"

  HEADS:
    NUM_CLASSES: 751

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

SOLVER:
  OPT: "Adam"
  MAX_ITER: 36000
  BASE_LR: 0.000175
  BIAS_LR_FACTOR: 1.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 32

  SCHED: "DelayedCosineAnnealingLR"

  DELAY_ITERS: 18000
  ETA_MIN_LR: 0.00000077

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 4000

  FREEZE_ITERS: 4000

  LOG_PERIOD: 400
  CHECKPOINT_PERIOD: 4001
  
TEST:
  PRECISE_BN:
    DATASET: 'Market1501'

OUTPUT_DIR: "logs/market1501/sbs-R101-ibn"
