_BASE_: "../Base-bagtricks.yml"

MODEL:
  HEADS:
    NUM_CLASSES: 9368
  LOSSES:
    CE:
      EPSILON: 0.1

DATASETS:
  NAMES: ("Fangdao_16stores",)
  TESTS: ("Fangdao_16stores",)

INPUT:
  SIZE_TRAIN: [224, 224]
  SIZE_TEST: [224, 224]
  DO_ROTATION: True
  REA:
    ENABLED: False
  DO_PAD: False

SOLVER:
  OPT: "Adam"
  MAX_ITER: 100000
  IMS_PER_BATCH: 64

  STEPS: [60000, 80000]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10000

  LOG_PERIOD: 200
  CHECKPOINT_PERIOD: 10000

TEST:
  EVAL_PERIOD: 10000

OUTPUT_DIR: "logs/Fangdao_16stores/bagtricks_R50-2"