_BASE_: "../Base-bagtricks.yml"


MODEL:

  OPEN_LAYERS: ["heads"]

  HEADS:
    NUM_CLASSES: 9368

    NAME: "BNneckHead"
    NORM: "BN"
    NECK_FEAT: "after"
    CLS_LAYER: "circle"
    POOL_LAYER: "gempool"
    SCALE: 64
    MARGIN: 0.35
    
  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss",)
    CE:
      EPSILON: 0.1
      SCALE: 1.0

    TRI:
      MARGIN: 0.0
      HARD_MINING: True
      NORM_FEAT: False
      SCALE: 1.0

DATASETS:
  NAMES: ("Fangdao_16stores",)
  TESTS: ("Fangdao_16stores",)

INPUT:
  SIZE_TRAIN: [224, 224]
  SIZE_TEST: [224, 224]
  DO_ROTATION: True
  REA:
    ENABLED: False
  DO_PAD: False

SOLVER:
  OPT: "Adam"
  MAX_ITER: 100000
  IMS_PER_BATCH: 64

  STEPS: [60000, 80000]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10000

  LOG_PERIOD: 200
  CHECKPOINT_PERIOD: 10000

TEST:
  EVAL_PERIOD: 10000

OUTPUT_DIR: "/hddc/ywu/logs/logs_fastreid/Fangdao_16stores/bagtricks_R50-3"