_BASE_: "../Base-Strongerbaseline.yml"

MODEL:
  HEADS:
    NUM_CLASSES: 20255

DATASETS:
  NAMES: ("Fangdao_74stores",)
  TESTS: ("Fangdao_74stores",)

INPUT:
  SIZE_TRAIN: [224, 224]
  SIZE_TEST: [224, 224]
  DO_ROTATION: True
  REA:
    ENABLED: False
  DO_PAD: False

SOLVER:
  OPT: "Adam"
  MAX_ITER: 200000
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  SCHED: "DelayedCosineAnnealingLR"

  DELAY_ITERS: 80000
  ETA_MIN_LR: 0.00000077

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 20000

  FREEZE_ITERS: 20000

  LOG_PERIOD: 200
  CHECKPOINT_PERIOD: 10000

TEST:
  EVAL_PERIOD: 10000
  PRECISE_BN:
    DATASET: 'Fangdao_74stores'

OUTPUT_DIR: "logs/fangdao/sbs_R50_fangdao74stores-10"