_BASE_: "../Base-Strongerbaseline.yml"

MODEL:
  BACKBONE:
    WITH_IBN: True
    PRETRAIN_PATH: "/home/ywu/.cache/torch/checkpoints/resnet50_ibn_a.pth.tar"
    NORM: 'syncBN'

  HEADS:
    NUM_CLASSES: 15365
    NORM: 'syncBN'

DATASETS:
  NAMES: ("Fangdao_Fanhua_35stores",)
  TESTS: ("Fangdao_Fanhua_35stores",)

INPUT:
  SIZE_TRAIN: [224, 224]
  SIZE_TEST: [224, 224]
  DO_ROTATION: True
  REA:
    ENABLED: False
  DO_PAD: False

SOLVER:
  OPT: "Adam"
  MAX_ITER: 160000
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  SCHED: "DelayedCosineAnnealingLR"

  DELAY_ITERS: 40000
  ETA_MIN_LR: 0.00000077

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10000

  FREEZE_ITERS: 10000

  LOG_PERIOD: 200
  CHECKPOINT_PERIOD: 10000

TEST:
  EVAL_PERIOD: 10000
  PRECISE_BN:
    DATASET: 'Fangdao_Fanhua_35stores'

OUTPUT_DIR: "/hddc/ywu/logs/logs_fastreid/Fangdao_Fanhua_35stores/sbs_R50_ibn_fanhua_fangdao35stores-3"